### ISSUE TITLE
Példa Projekt befejezése

### ISSUE THREAD

**Issue by AdamTakeow** [RFT-4th-team/cinemApp#1]
A jelenlegi állapota a projektnek egy hiányos példa alkalmazás, ami azt jelenti hogy az alkalmazás rétegek már készen vannak, viszont csak az adatbázis (jpa) rétegben van példa amivel szemléltethető hogy rendesen van minden bekonfigurálva.
A feladat az, hogy mindegyik rétegbe el kell készíteni azokat a forrásokat, amikkel ellenőrizhető hogy rendesen van minden konfigurálva. Az érintett rétegek: szolgáltatás (ejb) szolgáltatás api (ejb-api) megjelenítő réteg (web).

**Comment by NDBman** [comment]
Milyen forrásokat is?

**Comment by AdamTakeow** [comment]
Többek közt nincs még 1 szolgáltatás sem és ManagedBean-ek sincsenek a web rétegbe.
