### ISSUE TITLE
Error page css

### ISSUE THREAD

**Issue by NDBman** [RFT-4th-team/cinemApp#100]
Az error page-en nem jó a css. (logót nem tudja betölteni)

**Comment by NDBman** [comment]
http://5.249.154.6:8080/CinemApp-web/seatbooking.xhtml ezt a linket írtam be, bejött az error page de a logó továbbra sem :/ 

![Képernyőfotó 2016-12-06 - 1.25.02.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/K%C3%A9perny%C5%91fot%C3%B3%202016-12-06%20-%201.25.02-91182b2ad0a57f2ec2ca1a6a0cf5679df45366f032759bc8fae2685b01f11a2d.png)

**Comment by NDBman** [comment]
Such megoldás, Very okos, Much kreatív :D

**Comment by szanicsl** [comment]
Az volt vele a baj, ha az admin oldalon váltódik ki a könyvtárszerkezetben mélyebben van egyel, így vagy az admin oldalas hibánál nincs kép, vagy az összes többinél. :D Redirect-et nem lehet sajna ráerőszakolni, mikor egy kivétel váltódik ki.

**Comment by NDBman** [comment]
Ja én erről tudtam :D mm hogy ez a baj. de amúgy talán még jobb is így. Error pagesebb hangulata van hogy a fukciók nem érhetőek el rögtön onnan.

**Comment by NDBman** [comment]
Sőt néha hiába nyomtam egy funkcióra(pl szűrök) ugyanúgy az error page jött be tehát jobb ez így ez biztos.
