### ISSUE TITLE
QR kód hashelés

### ISSUE THREAD

**Issue by NDBman** [RFT-4th-team/cinemApp#107]
Biztonsági okokból a QR kódba kéne egy akkor legenerált kódot rakni, hogy ne lehessen visszaélni hamis foglalásokkal.

**Comment by szanicsl** [comment]
Ez szerintem nem feltétlenül szükséges, mert a foglalás ID-je is benne van a qr kódban, tehát az alapján meg lehet nézni, hogy tényleg az foglalt-e. Vélemény @AdamTakeow  @NDBman ?

**Comment by NDBman** [comment]
Igen ebben van valami amúgy, lehet tényleg nincs rá akkor szükség.
