### ISSUE TITLE
Képernyők elkészítése

### ISSUE THREAD

**Issue by AdamTakeow** [RFT-4th-team/cinemApp#14]
Az eddig kitalált és megtervezett felületek átöntése xhtml-be. Egyelőre elegendő beégetett adatokkal, majd ha a képernyők közötti navigáció és menni fog, illetve meglesznek az adatbázis kapcsolatok is, akkor mehetnek az éles adatok a felületre.

**Comment by szanicsl** [comment]
![2016-10-22 (2).png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/2016-10-22%20%282%29-1ef8ee4c6e86ad01573951304ec610ca9c2ec17fffe39c054fd53e09fb36b4e1.png)
![2016-10-22 (1).png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/2016-10-22%20%281%29-21fe86dd74d258bfa6e60c2d0291a2ab4de9185d5bfa2cd6221e836e7f224cea.png)

Alakul :)

**Comment by szanicsl** [comment]
![2016-10-22 (3).png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/2016-10-22%20%283%29-ea353f96c7b0ab7970892c7372cea686d8a956130a5f700dbcdf21a8c5bd5824.png)
![2016-10-22 (4).png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/2016-10-22%20%284%29-e2f1aa67c121df231cf06965b5c0bd841cab474d01ada073d9c5428f6bafffa2.png)
![2016-10-22 (5).png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/2016-10-22%20%285%29-82de71ff7407f5823cfec1224105748db8d68409b0acc926be2f93a6b1664209.png)

A filmek oldal is kész.
