### ISSUE TITLE
Navigáció a képernyők között

### ISSUE THREAD

**Issue by AdamTakeow** [RFT-4th-team/cinemApp#15]
Lehessen az elkészült képernyők között navigálni.

**Comment by szanicsl** [comment]
Ebben a témában mutattál egy példa kódot Ádám. Talán egy web.xml-ről. Erről tudnál linket adni? Köszönöm!

**Comment by AdamTakeow** [comment]
https://www.tutorialspoint.com/jsf/jsf_page_navigation.htm
