### ISSUE TITLE
Frissülő operációk

### ISSUE THREAD

**Issue by AdamTakeow** [RFT-4th-team/cinemApp#17]
El kellene érni valahogy, hogy ha egy kliensen történik egy művelet, akkor az kihasson minden többi kliensen is, tehát ha mondjuk van egy táblázatom gombokból, és ha egy gombot megnyomok akkor változik a színe, akkor ha valahol megnyomják a gombot és színes lesz, akkor az legyen mindenkinek színes.

**Comment by szanicsl** [comment]
Találtam rá egy egyszerű megoldást.
<h:form>
    <p:commandButton value="Foglalás" actionListener="#{seats.setNotFree()}" />
    <p:commandButton value="Foglalás lemondás" actionListener="#{seats.setFree()}" />
    <h:outputText id="free_or_not" value="#{seats.isFree()}" />
    <p:poll interval="1" listener="#{seats.getDataFromDatabase()}" update="free_or_not" />
</h:form>

Ahol az isFree() visszaadja, hogy "szabad", vagy "nem szabad" (String formájában), a getDataFromDatabase() pedig lekérdezi a szükséges táblát, és ez 1 másodperces intervallumokban lefut, és frissíti a szövegünket. A két gomb pedig egyértelmű. Lefoglalttá teszi az adatbázisban, vagy szabaddá teszi azt a helyet.

**Comment by AdamTakeow** [comment]
Na ez elég nehezen megoldható dolog, de megpróbálok mindent leírni erről a feladatról. Jelenleg BootsFaces-t használunk ami tud ugyan ajax operációkat, viszont ez kevés, mert csak basic ajax update cuccokat tud. Viszont van egy framework a RichFaces, ami pontosan tudja azt a műveletet, ami nekünk kell, (szerver oldalról triggerelhető frissítések, több képernyőn is frissül a tartalom) viszont ez nem kompatibilis a BootsFaces-zel. Későbbi megbeszélések során eldöntjük majd hogy mi legyen, (BootsFaces csere vagy megoldjuk külön oldalon a RichFaces-es dolgokat) addig is a következő módon lehet megnézni a funkciót: a szerveren, van egy xhtml (CinemApp-web/bookseat.xhtml) ami szemmel láthatóan nem tartalmaz BootsFaces elemeket (nem véletlenül) és ott van egy Push gomb  és egy aktuális dátum. A push gombot nyomogatva a dátum frissül "ajaxosan" tehát nem tölti újra az oldalt ami szükséges, és ugyanezt az oldalt megnyitva több helyen, mindenhol befrissül a push gomb hatására a dátum. Ez a művelet fog megfelelni a helyfoglalás műveletének!
