### ISSUE TITLE
Sql szkriptek

### ISSUE THREAD

**Issue by AdamTakeow** [RFT-4th-team/cinemApp#19]
Ha már lesznek adatok az adatbázisban, akkor létre kellene hozni egy sql fájlt amivel szinkronba lehet hozni a lokális adatbázisokat a szerveren lévő adatbázissal.

**Comment by szanicsl** [comment]
Az INSERT scripteket elvállalom, viszont ehhez először jó lenne, ha készen lennének a kapcsolatok is. CREATE script meg nem kell, mert a jpa elvégzi ezt helyettünk.
Kb. 2 admin, 3 felhasználó (guest), 5 film, 5 terem és ezekhez 30-30 hely elég lesz? Kupon, foglalás, stb. szerintem még nem kell, mert felesleges.

**Comment by AdamTakeow** [comment]
Már majdnem készen van, mert megcsináltam a kapcsolatokat és egyúttal feltöltöttem néhány példa inputtal is az adatbázist. Kell create script, mert ha create-re állítod a hbm2ddl property-t akkor kipucolja az adatbázist, és ha változni fognak a táblák szerkezetei akkor kell hogy a create script-tel feltöltse az adatbázist

**Comment by AdamTakeow** [comment]
A script fájl készen van, fel van töltve a jpa projektbe, ezt kellene minden alkalommal módosítani ha kell valamilyen adat ami meg kell jelenjen a szerveren
