### ISSUE TITLE
Travis CI deploy

### ISSUE THREAD

**Issue by AdamTakeow** [RFT-4th-team/cinemApp#20]
Utána kell nézni hogy hogy lehet megoldani hogy ha pushol valaki, akkor a projektet kitelepítse a szerveren futó wildfly-ra készre, működőre.

**Comment by szanicsl** [comment]
http://wecodetheweb.com/2015/08/27/automating-ftp-deployment-with-travis-ci-and-gulp/

Ezen a linkel található egy leírás a feladathoz. FTP kapcsolat segítségével megoldható az elkészült .ear fájlunk kitelepítése a webszerverre.

**Comment by AdamTakeow** [comment]
Köszi! Haladok vele

**Comment by AdamTakeow** [comment]
Ha közvetlenül a wildfly deployments mappájába van felmásolva ftp-vel, akkor egy picit gyorsabban észreveszi a wildfly hogy valamit deployolni akarok, mint hogy az ftp teljesen feltöltené a fájlt, ezért néha dobál olyan hibákat hogy hiányoznak dolgok a fájlból de elvileg ha teljesen feltöltötte, akkor rendesen deployol.

**Comment by AdamTakeow** [comment]
A feltöltés működik, egy kis probléma volt a jogosultságokkal, mert az ftp-s felhasználó által feltöltött fájlokat nem tudta olvasni a wildfly a deployhoz, viszont az ftp szerver beállításával megoldódott úgyhogy működik rendesen!
