### ISSUE TITLE
CinemApp logó tervezés

### ISSUE THREAD

**Issue by AdamTakeow** [RFT-4th-team/cinemApp#22]
Kellene tervezni egy vagány letisztult minimalista tetszetős tekintetet megragadó mindent elmondó beszédes mozi-helyfoglalós logót a webalkalmazásunkhoz :)

**Comment by szanicsl** [comment]
![logo.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/logo-4a1c002bad59b3fff3fe7ef559d661e2933d3d607a3f9d7c2ea7925e2308ea69.png)
Én erre gondoltam :)

**Comment by AdamTakeow** [comment]
Ez tökjó! még kellene egy olyan verzió is belőle amin rajta van a CinemApp felirat is, és akkor a felirat nélküli verzió mehetne page logónak meg olyan helyre ahova kicsi logó kell, a főoldalra meg mehetne a feliratos verziója!

**Comment by szanicsl** [comment]
![Logomakr_6llBnV.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Logomakr_6llBnV-21b029be8d1b6bef50f40cfd7c4987b85283f6fba679ed6af40425cc902ee3b6.png)
![Logomakr_6GXFYL.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Logomakr_6GXFYL-78ba288569cde4e6de2e8373357de063f1334924a6e594a32baf15b3d38e5728.png)

**Comment by szanicsl** [comment]
Az első képnél fehér a felirat, ezért nem látni itt Overv-ben :)
