### ISSUE TITLE
Movie tábla bővítése

### ISSUE THREAD

**Issue by szanicsl** [RFT-4th-team/cinemApp#27]
A movie táblát ki kell bővíteni két dologgal. Lehessen bele a filmekhez leírást adni (hosszabb szöveg, olyan max. 2000 karakter) illetve kell egy rövid azonosító, mellyel például a hozzá tartozó képeket, plakátokat tudjuk majd elnevezni a következő módon:
img src="#{movie.shortname}_poster.jpg", img src="#{movie.shortname}_1.jpg", img src="#{movie.shortname}_2.jpg", stb.

**Comment by AdamTakeow** [comment]
A két új field nevei: movieCode és description
