### ISSUE TITLE
Felület tervezése

### ISSUE THREAD

**Issue by AdamTakeow** [RFT-4th-team/cinemApp#3]
Meg kell tervezni hogy milyen oldalak lesznek és hogyan nézzenek ki.

**Comment by szanicsl** [comment]
![gyik.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/gyik-ce2005891d75a825b2c7290aebb13c9bef3575aaab08777f2d5558492f19ad4f.png)
!
[fooldal.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/fooldal-1daf884d65463bdcdca0ccaf5e0b5adb3dcbcec006b7d73640dce1dd76d77d42.png)
![filmek.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/filmek-d7d65b2f5a3740edf45228bcabc806387c1696cb8072e032f3d01c4136e506e3.png)
![kapcsolat.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/kapcsolat-84985585e5d97c3418aff90ad2aa874d2fba504380642f535a5c7b33c1354864.png)

**Comment by szanicsl** [comment]
A fejléc jobb felső sarkába jönne még egy login form
