### ISSUE TITLE
Bejelentkezés visszajelzések

### ISSUE THREAD

**Issue by AdamTakeow** [RFT-4th-team/cinemApp#30]
Bejelentkezéskor kell egy visszajelzés hogy sikeres-e vagy sikertelen, mert jelenleg nincs

**Comment by NDBman** [comment]
Egyelőre megcisnáltam annyit hogy egy label jelzi ott helyben , hogy be vagy-e jelentkezve vagy sem. De konkrétan miylen visszajelzést várunk? Átirányítást az admin felületre vagy egy új oldalra, hogy üdv, be vagy jelentkezve?

**Comment by AdamTakeow** [comment]
Ha sikeres a belépés, akkor a kezdő oldalra kell navigálnia, ha sikertelen akkor erről tájékoztatni kell a user-t így: http://showcase.bootsfaces.net/forms/messages.jsf;jsessionid=jWbHB4yc9GN6NWWSi4GD9ERL7IVGIcG-tZbopWP8.wildfly01

**Comment by NDBman** [comment]
Jólvan.
