### ISSUE TITLE
Css hiba

### ISSUE THREAD

**Issue by AdamTakeow** [RFT-4th-team/cinemApp#39]
Néhány oldalváltáskor széthullik a design, ki kell deríteni hogy mi okozza és megoldani. Csatolok képet

**Comment by AdamTakeow** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-8192c87b043e11dbc19c3ac74845a942ec493b5f6299f8c2dab8b2097eb80e85.png)
Itt még jó

**Comment by AdamTakeow** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e800cbb8fcb585be3918d02b427c832115af9c1b906aa23fb1d8b50cc1c01286.png)
itt már nem

**Comment by AdamTakeow** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-1a53d0cdd8945feb5b4dfe03ea7ad89de46e6b359e0a542e1b0c40997f2bb050.png)
itt sem

**Comment by szanicsl** [comment]
Ezek a hibák a lokális vagy a publikus szerveren jelentkeztek?

**Comment by szanicsl** [comment]
Ez a bug összefüggésben van az URL hibával, és azzal, hogy az adminpage.xml egy könyvtárral lejjebb található, így onnan nem ugyan azzal a path-al éri el a css file-t magát.

**Comment by AdamTakeow** [comment]
A problémát részben sikerült megoldanom a Template-s feladat megoldása közben a következő módon: a fő template oldalban használom a css-t és így: <h:outputStylesheet library="css" name="style.css" />. Ezzel minden oldalon jó már a css, viszont a képekhez a megfelelő működéshez a <h:graphicImage> taget használom. Az egyetlen gond ami még maradt az a CinemApp logó. Ez ugyanis a navbar-ba van egy elérhetőségi linkkel ami még mindig van hogy eltűnik, mert nem találja. Ezt még valahogy meg kellene oldani!

**Comment by AdamTakeow** [comment]
Valamiért a tag-ek eltűntek a kommentből, ezért leírom újra. A css-hez h:outputStylesheet tag-et, a képekhez pedig h:graphicImage tag-et hasznáok

**Comment by szanicsl** [comment]
Az URL bug kijavításával nekem ez is megoldódott. Beteszem TEST-be :)

**Comment by szanicsl** [comment]
Jelentkezett a hiba az admin oldalnál, az elérési út miatt. Létrehoztam egy securedLayout-ot is a secured oldalakhoz és egy securedHeader template-t is ennek kiküszöbölésére.

Kijavítva a bug, és tesztelve is. Zárom a taskot.
