### ISSUE TITLE
URL hiba

### ISSUE THREAD

**Issue by AdamTakeow** [RFT-4th-team/cinemApp#40]
A böngésző címsorában mindig az előző oldal url-je szerepel, nem az aktuális, ezt kellene kijavítani.

**Comment by szanicsl** [comment]
Megoldottam a hibát redirect-el, így mindig átirányítja az oldalt, és nem az előző oldalra tölti be a következőt.
Végignyomkodom az összes oldalon, és ha nem találok hibát, zárom a taskot.
