### ISSUE TITLE
Főoldal filmek

### ISSUE THREAD

**Issue by AdamTakeow** [RFT-4th-team/cinemApp#43]
A főoldalon megjelenő lapozóban valós filmek jelenjenek meg, az adatbázisból, plakáttal.

**Comment by AdamTakeow** [comment]
A tegnapi tesztelés alapján még van rajta finomítani való, hogy tökéletesen működjön, ezért visszarakom todo-ba

**Comment by szanicsl** [comment]
Kipróbáltam, és most működik. Teszteljétek majd ti is.

**Comment by AdamTakeow** [comment]
Működik!
