### ISSUE TITLE
Vetítések oldal

### ISSUE THREAD

**Issue by AdamTakeow** [RFT-4th-team/cinemApp#44]
Kell egy felület, ahol a kiválasztott filmhez megjelenítjük az időpontokat, amikor azt a filmet adják. Ezek az időpontok választhatók, és választáskor a helyfoglaló oldal következik. De a feladat egyelőre a felület és a kiválasztott filmhez tartozó időpontok megjelenítése.

**Comment by szanicsl** [comment]
Ez ugyan az, mint az #51-es feladat, így én ezt is Done-ba teszem. Ha pedig mégsem ugyan az, ezt jeleznéd @AdamTakeow ?

**Comment by AdamTakeow** [comment]
Igaz
