### ISSUE TITLE
Admin felület css

### ISSUE THREAD

**Issue by AdamTakeow** [RFT-4th-team/cinemApp#49]
Az admin felületen a tabok színe és a háttérszín közel azonos, ezzel és egyúttal csináljunk neki egy szép css-t hogy átláthatóbb legyen.

**Comment by szanicsl** [comment]
A gombok stílusát csak style=" " attribútummal tudtam megoldani, mert másképp nincs változás sem class-al sem id-val, sem styleClass-al, sem ha a b:commandbutton-re hivatkozik a css.

**Comment by AdamTakeow** [comment]
A tabok kimaradtak! :)

**Comment by szanicsl** [comment]
A tabok is ott vannak:)

**Comment by AdamTakeow** [comment]
Már látom!
