### ISSUE TITLE
Folyamatok megtervezése

### ISSUE THREAD

**Issue by AdamTakeow** [RFT-4th-team/cinemApp#5]
Kell egy leírás hogy milyen folyamatok játszódhatnak le, magyarul a funkciókról kell egy folyamat terv hogy mikor minek kell történnie (semmi konkrét csak afféle követelmény módon)

**Comment by AdamTakeow** [comment]
Nándi, órán nagyon penge voltál a folyamatokban, ezért téged bízlak meg ezzel a feladattal!

**Comment by NDBman** [comment]
Igenis!

**Comment by NDBman** [comment]
amúgy a folyamatokat hol tegyem közzé, hogy ti is láthassátok? @AdamTakeow  @szanicsl

**Comment by NDBman** [comment]
[filmkivalasztasa.vpp](https://drive.google.com/file/d/0B0BAY4hYH6I2dzFkcWFCOFFLZ1E/view?usp=drivesdk) [(download)](https://docs.google.com/uc?id=0B0BAY4hYH6I2dzFkcWFCOFFLZ1E&export=download "Download filmkivalasztasa.vpp")

**Comment by NDBman** [comment]
Egyelőre ez az egy van, aza  gond hogy nem jut eszembe több folyamat :D de ha ti tudtok mondjatok már.

**Comment by NDBman** [comment]
Egyelőre ez az egy van, aza  gond hogy nem jut eszembe több folyamat :D de ha ti tudtok mondjatok már.[filmkivalasztasa.vpp](https://drive.google.com/file/d/0B0BAY4hYH6I2VDRjanFxUVhkck0/view?usp=drivesdk) [(download)](https://docs.google.com/uc?id=0B0BAY4hYH6I2VDRjanFxUVhkck0&export=download "Download filmkivalasztasa.vpp")

**Comment by NDBman** [comment]
[![helyfoglalas.png](https://docs.google.com/uc?id=0B0BAY4hYH6I2RTI4Ui1RMVMwd0E&export=download)](https://drive.google.com/file/d/0B0BAY4hYH6I2RTI4Ui1RMVMwd0E/view?usp=drivesdk)

**Comment by AdamTakeow** [comment]
###Néhány folyamat: 
- Foglalás ✓ (kicsit lehetne részletesebb)
- Film hozzáadása adminisztrátor által
- Megnézett film értékelése (legyen külön folyamatban)
- Automatikus hely felszabadítások folyamata (rendszer által vendég nem szükséges)
 Hirtelen ennyi jutott eszembe, még majd kiegészíthetnénk valamivel

**Comment by AdamTakeow** [comment]
Ezt most már lassan be kellene fejezni

**Comment by NDBman** [comment]
Na feltöltöttem őket repóba egy külön resources mappába. A helyek automatikus felszabadítása szerintem így elég de nem tudtam mást kitalálni, ha van valami ötletetek szóljatok @AdamTakeow @szanicsl
