### ISSUE TITLE
Főoldal film választó

### ISSUE THREAD

**Issue by AdamTakeow** [RFT-4th-team/cinemApp#50]
A főoldalon jelenjen meg az összes film (nem carousel-ben) szépen plakátokkal és névvel. 1-1 plakátra kattintva jöjjön be a film leírása azaz egy Filmek menüpont alatt található filmek oldalhoz hasonló, de ezen az oldalon csak ez a film legyen és csak az ő információi.

**Comment by szanicsl** [comment]
Akkor egyúttal eldobjuk a carousel-t ezzel a főoldalról, vagy az maradjon meg, és alatta legyenek a filmek plakátjai?

**Comment by AdamTakeow** [comment]
Maradjon meg szerintem, mert jól néz ki hogy mutatja hogy milyen filmek vannak, de legyen ott alatta mindegyik film is külön, mert azokat lehet kiválasztani. Vagy, akár úgy is lehetne, hogy a carousel-ben 1 film van egyszerre csak, és az éppen aktuális filmre kattintva történne ugyanaz mint ami az alatta lévő filmekre, és akkor nem kellenek alulra a filmek (de valamit rakunk még azért oda alá hogy ne legyen csupasz :D )

**Comment by szanicsl** [comment]
Filmek lekérdezése és átirányítása működik az időpont választó felületre mind a carousel-ből, mind pedig a sima képekre kattintva.

**Comment by AdamTakeow** [comment]
Tesztelve! Szuperul megy!
