### ISSUE TITLE
Film időpontok

### ISSUE THREAD

**Issue by AdamTakeow** [RFT-4th-team/cinemApp#51]
az #50 feladat folytatása, hogy az #50-es feladat által elkészült oldalra kell egy fancy megoldás arra hogy kilistázzuk az időpontokat amikor ezt a filmet adják, termekkel. Ezek választhatóak legyenek, és a választás hatására következzen az ülőhely választás.

**Comment by szanicsl** [comment]
Megcsináltam az #50-es feladattal együtt, mivel nagyon összetartozóak. Választani lehet a vetítések közül, viszont még nincs megcsinálva az átirányítás a következő oldalra, ahol a foglalási folyamat megy végbe, mivel az majd a #52-es feladat része.

**Comment by AdamTakeow** [comment]
Tesztelve!
