### ISSUE TITLE
Időpont választó felület

### ISSUE THREAD

**Issue by AdamTakeow** [RFT-4th-team/cinemApp#52]
Kell egy időpont választó felület, ahol az összes vetítési időpontból lehet válogatni, és szűkíteni is lehet a keresést műfaj, hossz, és akár film szerint is. Ezt le is kellene tervezni, de ez egy külön feladat lesz. Tehát ez a feladat a megvalósításról szól.

**Comment by NDBman** [comment]
Most jelenleg az van, hogy napra lehet szűrni és úgy adja ki a filmeket aztán ha kiválasztod az egyiket akkor kiadja hogy az aznap milyen időpontokban lesz. Viszont akkor csináljam meg erre az oldalra a műfajszerinti szűrést is meg a többit? vagy az külön oldal lesz és végül megcisnáljuk tabosítva hogy időpont szűrő, műfaj szűrő, hossz szűrő stb? @AdamTakeow  @szanicsl

**Comment by NDBman** [comment]
By the way én a második megoldást ajánlanám :D

**Comment by szanicsl** [comment]
Szerintem simán műfaj szerinti szűrés legyen
