### ISSUE TITLE
Insert bug

### ISSUE THREAD

**Issue by AdamTakeow** [RFT-4th-team/cinemApp#58]
Amikor újraindul a szerver, és hozzá szeretnénk adni bármit, akkor nem adja hozzá és elszáll tipikusan PK megsértésével, hogy már van ilyen ID-val rekord. Ahogy nyomogatom, egyre nagyobb id-val próbálkozik, és amikor eléri a teszt adatok utolsó id-ját, onnantól kezdve jól működik. Tehát nem a meglévő id-kat folytatja, hanem 1-től kezdi keresni a szabad id-kat. Ezzel kezdeni kell valamit

**Comment by szanicsl** [comment]
Akkor is jelentkezik a bug, ha újra deploy-olunk a szerverre.

**Comment by AdamTakeow** [comment]
A problémát a generált azonosító kezdőértéke megoldotta.
