### ISSUE TITLE
Vetítés kezdése

### ISSUE THREAD

**Issue by AdamTakeow** [RFT-4th-team/cinemApp#62]
Vetítés kezdése előtt x idővel ne engedjen már foglalni az adott vetítésre. Ezt azzal érjük el, hogy nem tesszük választhatóvá ezeket az időpontokat a vendégek számára. (Meg sem jelenik már egyik választólistában sem.)

**Comment by szanicsl** [comment]
Más foglaláshoz híven 30 perccel előtte már nem fog megjelenni a vetítés a listában.
