### ISSUE TITLE
Dátum választó bug

### ISSUE THREAD

**Issue by szanicsl** [RFT-4th-team/cinemApp#63]
A dátum kiválasztásánál fel van cserélve a hónap és a nap, így formázásnál elromlik a dátum.

**Comment by AdamTakeow** [comment]
Ez a probléma hol jelentkezett?

**Comment by AdamTakeow** [comment]
A kupon műveleteknél 2 dátumválasztóban még továbbra is rosszul jelenik meg

**Comment by szanicsl** [comment]
Javítva
