### ISSUE TITLE
Filmek oldal design

### ISSUE THREAD

**Issue by AdamTakeow** [RFT-4th-team/cinemApp#88]
A feladat hogy a filmek oldalon a filmek és a plakátok egymás mellett és ne egymás alatt jelenjenek meg, így kicsit szebben nézne ki.

**Comment by AdamTakeow** [comment]
![Screenshot 2016-12-04 14.29.46.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Screenshot%202016-12-04%2014.29.46-d587071106c9e0bce4cbefbec8786d1833840d55ecaa3db5c52ad2f80d19524e.png)
Mellékelem az egyértelműség kedvéért ezt a precízen elkészített szabvány ábrát, amely pontosan szemlélteti az elemek elrendezését a képernyőn.

**Comment by szanicsl** [comment]
![Névtelen.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/N%C3%A9vtelen-3e10437f8efc25489760720d06ec8778375bc36af2d48772dc93695648019f8b.png)
:D
