### ISSUE TITLE
Valós email cím

### ISSUE THREAD

**Issue by szanicsl** [RFT-4th-team/cinemApp#9]
Meg kell oldani, hogy csak valós email címet lehessen megadni.

**Comment by NDBman** [comment]
Ez a LoginServiceImpl-be foglal majd helyett, ugye?

**Comment by AdamTakeow** [comment]
Nem, szerintem a meglévő email küldéses service-be kellene rakni

**Comment by szanicsl** [comment]
Itt annyi lenne a lényeg, hogy ne lehessen megadni nem email címet, mert különben lehal az email küldő
